<?php

namespace RefugeeBundle\Repository;

/**
 * campRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class campRepository extends \Doctrine\ORM\EntityRepository
{
}
