<?php

namespace RefugeeBundle\Repository;

/**
 * refugieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class refugieRepository extends \Doctrine\ORM\EntityRepository
{
}
